### ISSUE TITLE
Il y a un bug, UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined     at c (A:\Dev_Bot\MP4\node_modules\funcraft\structures\GamesStats.js:23:32)

### ISSUE THREAD

**Issue by Neyzn** [Androz2091/funcraft#23]
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at c (A:\Dev_Bot\MP4\node_modules\funcraft\structures\GamesStats.js:23:32)
```
Quand je met le code de base qui es dans le #README sa fait sa

**Comment by Androz2091** [comment]
Closed by #24
